# permissions for end users to view manilaapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manilaapi-viewer-role
rules:
- apiGroups:
  - manila.***REMOVED***.org
  resources:
  - manilaapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manila.***REMOVED***.org
  resources:
  - manilaapis/status
  verbs:
  - get
