/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group manila --version v1beta1 --kind Manila --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"

	rabbitmqv1 "github.com/openstack-k8s-operators/infra-operator/apis/rabbitmq/v1beta1"
	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	common_webhook "github.com/openstack-k8s-operators/lib-common/modules/common/webhook"
	"github.com/openstack-k8s-operators/lib-common/modules/common/util"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// ManilaDefaults -
type ManilaDefaults struct {
	APIContainerImageURL       string
	SchedulerContainerImageURL string
	ShareContainerImageURL     string
	DBPurgeAge                 int
	DBPurgeSchedule            string
	APITimeout                 int
}

var manilaDefaults ManilaDefaults

// log is for logging in this package.
var manilalog = logf.Log.WithName("manila-resource")

// SetupDefaults - initializes any CRD field defaults based on environment variables
// (the defaulting mechanism itself is implemented via webhooks)
func SetupDefaults() {
	// Acquire environmental defaults and initialize Manila defaults with them
	manilaDefaults = ManilaDefaults{
		APIContainerImageURL:       util.GetEnvVar("RELATED_IMAGE_MANILA_API_IMAGE_URL_DEFAULT", ManilaAPIContainerImage),
		SchedulerContainerImageURL: util.GetEnvVar("RELATED_IMAGE_MANILA_SCHEDULER_IMAGE_URL_DEFAULT", ManilaSchedulerContainerImage),
		ShareContainerImageURL:     util.GetEnvVar("RELATED_IMAGE_MANILA_SHARE_IMAGE_URL_DEFAULT", ManilaShareContainerImage),
		DBPurgeAge:                 DBPurgeDefaultAge,
		DBPurgeSchedule:            DBPurgeDefaultSchedule,
		APITimeout:                 APIDefaultTimeout,
	}

	manilalog.Info("Manila defaults initialized", "defaults", manilaDefaults)
}

var _ webhook.Defaulter = &Manila{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Manila) Default() {
	manilalog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Manila spec
func (spec *ManilaSpec) Default() {
	// only put container image validations here
	if spec.ManilaAPI.ContainerImage == "" {
		spec.ManilaAPI.ContainerImage = manilaDefaults.APIContainerImageURL
	}

	if spec.ManilaScheduler.ContainerImage == "" {
		spec.ManilaScheduler.ContainerImage = manilaDefaults.SchedulerContainerImageURL
	}

	for key, manilaShare := range spec.ManilaShares {
		if manilaShare.ContainerImage == "" {
			manilaShare.ContainerImage = manilaDefaults.ShareContainerImageURL
			// This is required, as the loop variable is a by-value copy
			spec.ManilaShares[key] = manilaShare
		}
	}
	spec.ManilaSpecBase.Default()

}

// Default - set defaults for this Manila spec base
func (spec *ManilaSpecBase) Default() {
	// Default MessagingBus with cluster name from RabbitMqClusterName
	// Only migrate from deprecated field if the new field is not already set
	if spec.MessagingBus.Cluster == "" {
		rabbitmqv1.DefaultRabbitMqConfig(&spec.MessagingBus, spec.RabbitMqClusterName)
	}

	// Default NotificationsBus if NotificationsBusInstance is specified
	if spec.NotificationsBusInstance != nil && *spec.NotificationsBusInstance != "" {
		if spec.NotificationsBus == nil {
			// Initialize empty NotificationsBus - credentials will be created dynamically
			// to ensure separation from MessagingBus (RPC and notifications should never share credentials)
			spec.NotificationsBus = &rabbitmqv1.RabbitMqConfig{}
		}
		rabbitmqv1.DefaultRabbitMqConfig(spec.NotificationsBus, *spec.NotificationsBusInstance)
	}

	if spec.APITimeout == 0 {
		spec.APITimeout = manilaDefaults.APITimeout
	}

	if spec.DBPurge.Age == 0 {
		spec.DBPurge.Age = manilaDefaults.DBPurgeAge
	}

	if spec.DBPurge.Schedule == "" {
		spec.DBPurge.Schedule = manilaDefaults.DBPurgeSchedule
	}
}

// Default - set defaults for this Manila spec core. This version is used by OpenStackControlplane
func (spec *ManilaSpecCore) Default() {

	spec.ManilaSpecBase.Default()
}

// getDeprecatedFields returns the centralized list of deprecated fields for ManilaSpecBase
func (spec *ManilaSpecBase) getDeprecatedFields(old *ManilaSpecBase) []common_webhook.DeprecatedFieldUpdate {
	// Get new field value (handle nil NotificationsBus)
	var newNotifBusCluster *string
	if spec.NotificationsBus != nil {
		newNotifBusCluster = &spec.NotificationsBus.Cluster
	}

	deprecatedFields := []common_webhook.DeprecatedFieldUpdate{
		{
			DeprecatedFieldName: "rabbitMqClusterName",
			NewFieldPath:        []string{"messagingBus", "cluster"},
			NewDeprecatedValue:  &spec.RabbitMqClusterName,
			NewValue:            &spec.MessagingBus.Cluster,
		},
		{
			DeprecatedFieldName: "notificationsBusInstance",
			NewFieldPath:        []string{"notificationsBus", "cluster"},
			NewDeprecatedValue:  spec.NotificationsBusInstance,
			NewValue:            newNotifBusCluster,
		},
	}

	// If old spec is provided (UPDATE operation), add old values
	if old != nil {
		deprecatedFields[0].OldDeprecatedValue = &old.RabbitMqClusterName
		deprecatedFields[1].OldDeprecatedValue = old.NotificationsBusInstance
	}

	return deprecatedFields
}

// validateDeprecatedFieldsCreate validates deprecated fields during CREATE operations
func (spec *ManilaSpecBase) validateDeprecatedFieldsCreate(basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list (without old values for CREATE)
	deprecatedFieldsUpdate := spec.getDeprecatedFields(nil)

	// Convert to DeprecatedField list for CREATE validation
	deprecatedFields := make([]common_webhook.DeprecatedField, len(deprecatedFieldsUpdate))
	for i, df := range deprecatedFieldsUpdate {
		deprecatedFields[i] = common_webhook.DeprecatedField{
			DeprecatedFieldName: df.DeprecatedFieldName,
			NewFieldPath:        df.NewFieldPath,
			DeprecatedValue:     df.NewDeprecatedValue,
			NewValue:            df.NewValue,
		}
	}

	return common_webhook.ValidateDeprecatedFieldsCreate(deprecatedFields, basePath), nil
}

// validateDeprecatedFieldsUpdate validates deprecated fields during UPDATE operations
func (spec *ManilaSpecBase) validateDeprecatedFieldsUpdate(old ManilaSpecBase, basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list with old values
	deprecatedFields := spec.getDeprecatedFields(&old)
	return common_webhook.ValidateDeprecatedFieldsUpdate(deprecatedFields, basePath)
}

var _ webhook.Validator = &Manila{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateCreate() (admission.Warnings, error) {
	manilalog.Info("validate create", "name", r.Name)

	basePath := field.NewPath("spec")
	warnings, allErrs := r.Spec.ValidateCreate(basePath, r.Namespace)

	if len(allErrs) != 0 {
		return warnings, apierrors.NewInvalid(
			schema.GroupKind{Group: "manila.openstack.org", Kind: "Manila"},
			r.Name, allErrs)
	}

	return warnings, nil
}

// ValidateCreate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an manila spec.
func (spec *ManilaSpec) ValidateCreate(basePath *field.Path, namespace string) (admission.Warnings, field.ErrorList) {
	var allErrs field.ErrorList
	var warnings admission.Warnings

	// Validate deprecated fields
	deprecatedWarnings, deprecatedErrors := spec.ManilaSpecBase.validateDeprecatedFieldsCreate(basePath)
	warnings = append(warnings, deprecatedWarnings...)
	allErrs = append(allErrs, deprecatedErrors...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("manilaAPI").Child("override").Child("service"),
		spec.ManilaAPI.Override.Service)...)

	allErrs = append(allErrs, spec.ValidateManilaTopology(basePath, namespace)...)
	return warnings, allErrs
}

// ValidateCreate -
func (spec *ManilaSpecCore) ValidateCreate(basePath *field.Path, namespace string) (admission.Warnings, field.ErrorList) {
	var allErrs field.ErrorList
	var warnings admission.Warnings

	// Validate deprecated fields
	deprecatedWarnings, deprecatedErrors := spec.ManilaSpecBase.validateDeprecatedFieldsCreate(basePath)
	warnings = append(warnings, deprecatedWarnings...)
	allErrs = append(allErrs, deprecatedErrors...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("manilaAPI").Child("override").Child("service"),
		spec.ManilaAPI.Override.Service)...)

	allErrs = append(allErrs, spec.ValidateManilaTopology(basePath, namespace)...)
	return warnings, allErrs
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	manilalog.Info("validate update", "name", r.Name)

	oldManila, ok := old.(*Manila)
	if !ok || oldManila == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	basePath := field.NewPath("spec")
	warnings, allErrs := r.Spec.ValidateUpdate(oldManila.Spec, basePath, r.Namespace)

	if len(allErrs) != 0 {
		return warnings, apierrors.NewInvalid(
			schema.GroupKind{Group: "manila.openstack.org", Kind: "Manila"},
			r.Name, allErrs)
	}

	return warnings, nil
}

// ValidateUpdate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an manila spec.
func (spec *ManilaSpec) ValidateUpdate(old ManilaSpec, basePath *field.Path, namespace string) (admission.Warnings, field.ErrorList) {
	var allErrs field.ErrorList
	var warnings admission.Warnings

	// Validate deprecated fields
	deprecatedWarnings, deprecatedErrors := spec.ManilaSpecBase.validateDeprecatedFieldsUpdate(old.ManilaSpecBase, basePath)
	warnings = append(warnings, deprecatedWarnings...)
	allErrs = append(allErrs, deprecatedErrors...)

	// validate the service base parameters
	allErrs = append(allErrs, spec.ValidateBaseParams(basePath)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("manilaAPI").Child("override").Child("service"),
		spec.ManilaAPI.Override.Service)...)

	allErrs = append(allErrs, spec.ValidateManilaTopology(basePath, namespace)...)

	return warnings, allErrs
}

// ValidateUpdate -
func (spec *ManilaSpecCore) ValidateUpdate(old ManilaSpecCore, basePath *field.Path, namespace string) (admission.Warnings, field.ErrorList) {
	var allErrs field.ErrorList
	var warnings admission.Warnings

	// Validate deprecated fields
	deprecatedWarnings, deprecatedErrors := spec.ManilaSpecBase.validateDeprecatedFieldsUpdate(old.ManilaSpecBase, basePath)
	warnings = append(warnings, deprecatedWarnings...)
	allErrs = append(allErrs, deprecatedErrors...)

	// validate the service base parameters
	allErrs = append(allErrs, spec.ValidateBaseParams(basePath)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("manilaAPI").Child("override").Child("service"),
		spec.ManilaAPI.Override.Service)...)

	allErrs = append(allErrs, spec.ValidateManilaTopology(basePath, namespace)...)
	return warnings, allErrs
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateDelete() (admission.Warnings, error) {
	manilalog.Info("validate delete", "name", r.Name)

	return nil, nil
}

// SetDefaultRouteAnnotations sets HAProxy timeout values of the route
func (spec *ManilaSpecCore) SetDefaultRouteAnnotations(annotations map[string]string) {
	const haProxyAnno = "haproxy.router.openshift.io/timeout"
	// Use a custom annotation to flag when the operator has set the default HAProxy timeout
	// With the annotation func determines when to overwrite existing HAProxy timeout with the APITimeout
	const manilaAnno = "api.manila.openstack.org/timeout"

	valManila, okManila := annotations[manilaAnno]
	valHAProxy, okHAProxy := annotations[haProxyAnno]

	// Human operator set the HAProxy timeout manually
	if !okManila && okHAProxy {
		return
	}

	// Human operator modified the HAProxy timeout manually without removing the Manila flag
	if okManila && okHAProxy && valManila != valHAProxy {
		delete(annotations, manilaAnno)
		return
	}

	timeout := fmt.Sprintf("%ds", spec.APITimeout)
	annotations[manilaAnno] = timeout
	annotations[haProxyAnno] = timeout
}

// ValidateManilaTopology - Returns an ErrorList if the Topology is referenced
// on a different namespace
func (spec *ManilaSpecCore) ValidateManilaTopology(basePath *field.Path, namespace string) field.ErrorList {
	var allErrs field.ErrorList

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	// When a TopologyRef CR is referenced with an override to ManilaAPI, fail
	// if a different Namespace is referenced because not supported
	apiPath := basePath.Child("manilaAPI")
	allErrs = append(allErrs,
		spec.ManilaAPI.ValidateTopology(apiPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to ManilaScheduler,
	// fail if a different Namespace is referenced because not supported
	scPath := basePath.Child("manilaScheduler")
	allErrs = append(allErrs,
		spec.ManilaScheduler.ValidateTopology(scPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to an instance of
	// ManilaShares, fail if a different Namespace is referenced because not
	// supported
	for k, ms := range spec.ManilaShares {
		path := basePath.Child("manilaShares").Key(k)
		allErrs = append(allErrs, ms.ValidateTopology(path, namespace)...)
	}
	return allErrs
}

// ValidateManilaTopology - Returns an ErrorList if the Topology is referenced
// on a different namespace
func (spec *ManilaSpec) ValidateManilaTopology(basePath *field.Path, namespace string) field.ErrorList {
	var allErrs field.ErrorList

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	// When a TopologyRef CR is referenced with an override to ManilaAPI, fail
	// if a different Namespace is referenced because not supported
	apiPath := basePath.Child("manilaAPI")
	allErrs = append(allErrs,
		spec.ManilaAPI.ValidateTopology(apiPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to ManilaScheduler,
	// fail if a different Namespace is referenced because not supported
	scPath := basePath.Child("manilaScheduler")
	allErrs = append(allErrs,
		spec.ManilaScheduler.ValidateTopology(scPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to an instance of
	// ManilaShares, fail if a different Namespace is referenced because not
	// supported
	for k, ms := range spec.ManilaShares {
		path := basePath.Child("manilaShares").Key(k)
		allErrs = append(allErrs, ms.ValidateTopology(path, namespace)...)
	}
	return allErrs
}

// ValidateBaseParams -
func (spec *ManilaSpec) ValidateBaseParams(basePath *field.Path) field.ErrorList {
	var allErrs field.ErrorList
	if spec.RabbitMqClusterName == "" {
		rabbitPath := basePath.Child("rabbitMqClusterName")
		allErrs = append(allErrs,
			field.Invalid(rabbitPath, "rabbitMqClusterName", "RabbitMqClusterName is empty"))
	}
	if spec.MemcachedInstance == "" {
		mcPath := basePath.Child("memcachedInstance")
		allErrs = append(allErrs,
			field.Invalid(mcPath, "memcachedInstance", "MemcachedInstance is empty"))
	}
	if spec.DatabaseAccount == "" {
		dbAcc := basePath.Child("databaseAccount")
		allErrs = append(allErrs,
			field.Invalid(dbAcc, "databaseAccount", "DatabaseAccount is empty"))
	}
	return allErrs
}

// ValidateBaseParams -
func (spec *ManilaSpecCore) ValidateBaseParams(basePath *field.Path) field.ErrorList {
	var allErrs field.ErrorList
	if spec.RabbitMqClusterName == "" {
		rabbitPath := basePath.Child("rabbitMqClusterName")
		allErrs = append(allErrs,
			field.Invalid(rabbitPath, "rabbitMqClusterName", "RabbitMqClusterName is empty"))
	}
	if spec.MemcachedInstance == "" {
		mcPath := basePath.Child("memcachedInstance")
		allErrs = append(allErrs,
			field.Invalid(mcPath, "memcachedInstance", "MemcachedInstance is empty"))
	}
	if spec.DatabaseAccount == "" {
		dbAcc := basePath.Child("databaseAccount")
		allErrs = append(allErrs,
			field.Invalid(dbAcc, "databaseAccount", "DatabaseAccount is empty"))
	}
	return allErrs
}
