/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group manila --version v1beta1 --kind Manila --programmatic-validation --defaulting
//

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/util"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// ManilaDefaults -
type ManilaDefaults struct {
	APIContainerImageURL       string
	SchedulerContainerImageURL string
	ShareContainerImageURL     string
	DBPurgeAge                 int
	DBPurgeSchedule            string
}

var manilaDefaults ManilaDefaults

// log is for logging in this package.
var manilalog = logf.Log.WithName("manila-resource")

// SetupDefaults - initializes any CRD field defaults based on environment variables
// (the defaulting mechanism itself is implemented via webhooks)
func SetupDefaults() {
	// Acquire environmental defaults and initialize Manila defaults with them
	manilaDefaults = ManilaDefaults{
		APIContainerImageURL:       util.GetEnvVar("RELATED_IMAGE_MANILA_API_IMAGE_URL_DEFAULT", ManilaAPIContainerImage),
		SchedulerContainerImageURL: util.GetEnvVar("RELATED_IMAGE_MANILA_SCHEDULER_IMAGE_URL_DEFAULT", ManilaSchedulerContainerImage),
		ShareContainerImageURL:     util.GetEnvVar("RELATED_IMAGE_MANILA_SHARE_IMAGE_URL_DEFAULT", ManilaShareContainerImage),
		DBPurgeAge:                 DBPurgeDefaultAge,
		DBPurgeSchedule:            DBPurgeDefaultSchedule,
	}

	manilalog.Info("Manila defaults initialized", "defaults", manilaDefaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *Manila) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-manila-openstack-org-v1beta1-manila,mutating=true,failurePolicy=fail,sideEffects=None,groups=manila.openstack.org,resources=manilas,verbs=create;update,versions=v1beta1,name=mmanila.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &Manila{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Manila) Default() {
	manilalog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Manila spec
func (spec *ManilaSpec) Default() {
	if spec.ManilaAPI.ContainerImage == "" {
		spec.ManilaAPI.ContainerImage = manilaDefaults.APIContainerImageURL
	}

	if spec.ManilaScheduler.ContainerImage == "" {
		spec.ManilaScheduler.ContainerImage = manilaDefaults.SchedulerContainerImageURL
	}

	for key, manilaShare := range spec.ManilaShares {
		if manilaShare.ContainerImage == "" {
			manilaShare.ContainerImage = manilaDefaults.ShareContainerImageURL
			// This is required, as the loop variable is a by-value copy
			spec.ManilaShares[key] = manilaShare
		}
	}

	if spec.DBPurge.Age == 0 {
		spec.DBPurge.Age = manilaDefaults.DBPurgeAge
	}

	if spec.DBPurge.Schedule == "" {
		spec.DBPurge.Schedule = manilaDefaults.DBPurgeSchedule
	}
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-manila-openstack-org-v1beta1-manila,mutating=false,failurePolicy=fail,sideEffects=None,groups=manila.openstack.org,resources=manilas,verbs=create;update,versions=v1beta1,name=vmanila.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &Manila{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateCreate() error {
	manilalog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateUpdate(old runtime.Object) error {
	manilalog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Manila) ValidateDelete() error {
	manilalog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil
}
