/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package manila

import (
	"github.com/openstack-k8s-operators/lib-common/modules/storage"
	ctrl "sigs.k8s.io/controller-runtime"
	"time"
)

const (
	// ServiceName - API V1 service name, deprecated
	ServiceName = "manila"
	// ServiceType - API V1 service type, deprecated
	ServiceType = "share"
	// ServiceNameV2 - API V2 service name, supported
	ServiceNameV2 = "manilav2"
	// ServiceTypeV2 - API V2 service type, supported
	ServiceTypeV2 = "sharev2"

	// DatabaseName - Name of the database used in CREATE DATABASE statement
	DatabaseName = "manila"
	// DatabaseCRName - Name of the MariaDBDatabase CR
	DatabaseCRName = "manila"
	// DatabaseUsernamePrefix - used by EnsureMariaDBAccount when a new username
	// is to be generated, e.g. "manila_e5a4", "manila_78bc", etc
	DatabaseUsernamePrefix = "manila"

	// Manila's uid and gid magic numbers come from the 'manila-user' in
	// https://github.com/openstack/kolla/blob/master/kolla/common/users.py

	// ManilaUserID -
	ManilaUserID int64 = 42429
	// ManilaGroupID -
	ManilaGroupID int64 = 42429

	// ManilaPublicPort -
	ManilaPublicPort int32 = 8786
	// ManilaInternalPort -
	ManilaInternalPort int32 = 8786

	// ManilaExtraVolTypeUndefined can be used to label an extraMount which
	// is not associated with a specific backend
	ManilaExtraVolTypeUndefined storage.ExtraVolType = "Undefined"
	// ManilaExtraVolTypeCeph can be used to label an extraMount which
	// is associated to a Ceph backend
	ManilaExtraVolTypeCeph storage.ExtraVolType = "Ceph"
	// ManilaShare is the definition of the manila-share group
	ManilaShare storage.PropagationType = "ManilaShare"
	// ManilaScheduler is the definition of the manila-scheduler group
	ManilaScheduler storage.PropagationType = "ManilaScheduler"
	// ManilaAPI is the definition of the manila-api group
	ManilaAPI storage.PropagationType = "ManilaAPI"
	// Manila is the global ServiceType that refers to all the components deployed
	// by the manila operator
	Manila storage.PropagationType = "Manila"
	// DefaultsConfigFileName - Provided by Manila umbrella controller
	DefaultsConfigFileName = "00-config.conf"
	// ServiceConfigFileName - Represents service config generated in the operator
	ServiceConfigFileName = "01-config.conf"
	// CustomConfigFileName - Config snippets inherited by the top-level CR
	CustomConfigFileName = "02-config.conf"
	// CustomServiceConfigFileName - Config snippets defined for the sub CR
	CustomServiceConfigFileName = "03-config.conf"
	// CustomServiceConfigSecretsFileName - Snippet generated by Secrets passed
	// to the sub CR
	CustomServiceConfigSecretsFileName = "04-config.conf"
	// ShortDuration -
	ShortDuration = time.Duration(5) * time.Second
	// NormalDuration -
	NormalDuration = time.Duration(10) * time.Second
	//DBSyncCommand -
	DBSyncCommand = "/usr/bin/manila-manage --config-dir /etc/manila/manila.conf.d db sync"
)

// DbsyncPropagation keeps track of the DBSync Service Propagation Type
var DbsyncPropagation = []storage.PropagationType{storage.DBSync}

// ManilaSchedulerPropagation is the  definition of the ManilaScheduler propagation group
// It allows the ManilaScheduler pod to mount volumes destined to Manila and ManilaScheduler
// ServiceTypes
var ManilaSchedulerPropagation = []storage.PropagationType{Manila, ManilaScheduler}

// ManilaAPIPropagation is the  definition of the ManilaAPI propagation group
// It allows the ManilaAPI pod to mount volumes destined to Manila and ManilaAPI
// ServiceTypes
var ManilaAPIPropagation = []storage.PropagationType{Manila, ManilaAPI}

// ManilaSharePropagation is the  definition of the ManilaShare propagation group
// It allows the ManilaShare pods to mount volumes destined to Manila and ManilaShare
// ServiceTypes
var ManilaSharePropagation = []storage.PropagationType{Manila, ManilaShare}

// ResultRequeue - Used to requeue a request
var ResultRequeue = ctrl.Result{RequeueAfter: NormalDuration}
