---
apiVersion: v1
kind: Secret
metadata:
  name: osp-secret-manila-netapp
  namespace: openstack
stringData:
  netapp-secrets.conf : |
    [netapp]
    netapp_server_hostname = 1.2.3.4
    netapp_login = fancy_netapp_user
    netapp_password = secret_netapp_password
    netapp_vserver = mydatavserver
