ServerTokens Prod
ServerSignature Off
TraceEnable Off
ServerRoot "/etc/httpd"
ServerName "manila.openstack.svc"

User manila
Group manila

Listen 8786

TypesConfig /etc/mime.types

Include conf.modules.d/*.conf

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
CustomLog /dev/stdout combined env=!forwarded
CustomLog /dev/stdout proxy env=forwarded
ErrorLog /dev/stdout

Include conf.d/*.conf
